// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mas_api.Data;

#nullable disable

namespace masapi.Migrations
{
    [DbContext(typeof(MasDbContext))]
    [Migration("20250811194505_AddTamales")]
    partial class AddTamales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("mas_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("mas_api.Models.Tamal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Envoltura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioDocena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioMediaDocena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relleno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tamales");
                });
#pragma warning restore 612, 618
        }
    }
}
